# Automatically fetches the latest API spec (and commits the submodule update) and generates a new client
name: Generate Client

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.ACTIONS_PAT }}
        submodules: true
        
    - name: Git Submodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive
        
    - name: Commit update
      run: |
        git config --global user.name 'Git bot'
        git config --global user.email 'bot@noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}
        git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"

#     - name: Set up Go
#       uses: actions/setup-go@v3
#       with:
#         go-version: 1.19

#     - name: Build
#       run: go build -v ./...

#     - name: Test
#       run: go test -v ./...
